backend:
  name: github
  repo: dragonprojects/dragonroleplay
  open_authoring: true

publish_mode: editorial_workflow

logo_url: /assets/logo.png
public_folder: "/assets"
media_folder: "docs/assets"

collections:
  - name: "characters"
    label: "Characters"
    label_singular: "Character"
    folder: "docs/characters"
    create: true
    slug: "{{slug}}"
    preview_path: characters/{{filename}}
    summary: "{{filename}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}
