backend:
  name: github
  repo: jelle619/dragonrp
  open_authoring: true

publish_mode: editorial_workflow

logo_url: ../assets/logo.png
public_folder: "wiki/assets"
media_folder: "docs/assets"

collections:
  - name: "root"
    label: "Root"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    preview_path: wiki/{{filename}}
    summary: "{{filename}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "culture"
    label: "Culture"
    folder: "docs/culture"
    create: true
    slug: "{{slug}}"
    preview_path: wiki/culture/{{filename}}
    summary: "{{filename}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "innerworkings"
    label: "Innerworkings"
    folder: "docs/innerworkings"
    create: true
    slug: "{{slug}}"
    preview_path: wiki/innerworkings/{{filename}}
    summary: "{{filename}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "organisations"
    label: "Organisations"
    folder: "docs/organisations"
    create: true
    slug: "{{slug}}"
    preview_path: wiki/organisations/{{filename}}
    summary: "{{filename}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "roleplay"
    label: "Roleplay"
    folder: "docs/roleplay"
    create: true
    slug: "{{slug}}"
    preview_path: wiki/roleplay/{{filename}}
    summary: "{{filename}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "species"
    label: "Species"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    preview_path: wiki/species/{{filename}}
    summary: "{{filename}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "plot"
    label: "Plot"
    folder: "docs/plot"
    create: true
    slug: "{{slug}}"
    preview_path: wiki/plot/{{filename}}
    summary: "{{filename}}"
    fields:
      - {label: "Body", name: "body", widget: "markdown"}
