backend:
  name: github
  repo: jelle619/dragonrp
  open_authoring: true

publish_mode: editorial_workflow

logo_url: ../assets/logo.png
public_folder: "wiki/assets"
media_folder: "docs/assets"

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    preview_path: wiki/{{filename}}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
